### ISSUE TITLE
GPGME

### ISSUE THREAD

**Issue by worf1337** [AlienCowEatCake/sylpheed-macos#7]
hey,

any way to build this with GPGME support? I don't understand bash very well, sorry...

**Comment by AlienCowEatCake** [comment]
I added support for GPGME in [6b04b09](https://github.com/AlienCowEatCake/sylpheed-macos/commit/6b04b0902badd9d9be9aa3f9b7f1a69c68a8e172), `master` branch. I tested the signature verification with gpgme package from [Homebrew](https://brew.sh/) and [MacPorts](https://www.macports.org/). [GPG Suite](https://gpgtools.org/) works also. I not tested all features, but it looks like everything should work

Binary builds will be later, in a few hours or tomorrow

**Comment by AlienCowEatCake** [comment]
GPGME is available in the latest release https://github.com/AlienCowEatCake/sylpheed-macos/releases/tag/sylpheed-3.8.0beta1-4

**Comment by worf1337** [comment]
thank you, appreciate this
